// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRSXm4rtab9wHNOVp9f18VyvhM5KpZHMw',
    appId: '1:547006099680:web:e1b94eae92a67ba4562085',
    messagingSenderId: '547006099680',
    projectId: 'delapp-47503',
    authDomain: 'delapp-47503.firebaseapp.com',
    storageBucket: 'delapp-47503.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpg7PSaGchWWIDs0zwue_FclEAK3yQsmA',
    appId: '1:547006099680:android:12a036048a50bc61562085',
    messagingSenderId: '547006099680',
    projectId: 'delapp-47503',
    storageBucket: 'delapp-47503.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqxwWRqDrRvZaK2XXnEOzavILQ6lv3pm0',
    appId: '1:547006099680:ios:4e7d67758857a121562085',
    messagingSenderId: '547006099680',
    projectId: 'delapp-47503',
    storageBucket: 'delapp-47503.appspot.com',
    iosClientId: '547006099680-ebvev3orvqucsm4e5eue828co9fg56ft.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqxwWRqDrRvZaK2XXnEOzavILQ6lv3pm0',
    appId: '1:547006099680:ios:7cf8ab54a1aa1d1a562085',
    messagingSenderId: '547006099680',
    projectId: 'delapp-47503',
    storageBucket: 'delapp-47503.appspot.com',
    iosClientId: '547006099680-rpeod7tj7v7rvkscf5t3rg6odlvkls97.apps.googleusercontent.com',
    iosBundleId: 'com.example.deliveryx.RunnerTests',
  );
}
